# Functions of DataFrame 5

**정규화 : X-min/max-min**

In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, minmax_scale, Binarizer, binarize

In [4]:
X=np.array([[10.,-10., 1.],
             [2., 3., 1.7],
             [0., 10., 3.]])

In [5]:
print((X-X.mean(axis=0))/(X.max(axis=0)-X.min(axis=0)))

[[ 0.6  -0.55 -0.45]
 [-0.2   0.1  -0.1 ]
 [-0.4   0.45  0.55]]


In [6]:
mms=MinMaxScaler()
xmms=mms.fit_transform(X)
print(xmms)

[[1.   0.   0.  ]
 [0.2  0.65 0.35]
 [0.   1.   1.  ]]


In [7]:
xmms2=minmax_scale(X,axis=0,copy=True)
print(xmms2)

[[1.   0.   0.  ]
 [0.2  0.65 0.35]
 [0.   1.   1.  ]]


**이진화**

In [8]:
X=np.array([[10.,-10., 1.],
             [2., 3., 1.7],
             [0., 10., 3.]])

In [9]:
binarizer=Binarizer().fit(X)
print(binarizer)

Binarizer(copy=True, threshold=0.0)


In [10]:
print(binarizer.transform(X))

[[1. 0. 1.]
 [1. 1. 1.]
 [0. 1. 1.]]


In [12]:
binarizer=Binarizer(threshold=2.0)
print(binarizer)
print(binarizer.transform(X))

Binarizer(copy=True, threshold=2.0)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 1.]]


In [13]:
print(binarize(X,threshold=2.0, copy=False))
print(X)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 1.]]


**OneHotEncoding**

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [15]:
data_train=np.array([[0,0,0],
                     [0, 1, 1],
                     [0, 2, 2],
                     [1, 0, 3],
                     [1, 1, 4]])

In [16]:
enc=OneHotEncoder()
print(enc.fit(data_train))

OneHotEncoder(categorical_features='all', dtype=<class 'numpy.float64'>,
       handle_unknown='error', n_values='auto', sparse=True)


In [17]:
print(enc.active_features_)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
print(enc.n_values_)

[2 3 5]


In [20]:
print(enc.feature_indices_)

[ 0  2  5 10]


In [21]:
data_new=np.array([[1,2,3]])
print(enc.transform(data_new).toarray())

[[0. 1. 0. 0. 1. 0. 0. 0. 1. 0.]]
