# Functions of Numpy 6

In [1]:
import pandas as pd
from pandas import DataFrame as df
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df_1=df(data=np.arange(12).reshape(3,4),
        index=['r0','r1','r2'],
        dtype='int',
        columns=['c0','c1','c2','c3'])

In [3]:
print(df_1)

    c0  c1  c2  c3
r0   0   1   2   3
r1   4   5   6   7
r2   8   9  10  11


In [4]:
print(df_1.T)

    r0  r1  r2
c0   0   4   8
c1   1   5   9
c2   2   6  10
c3   3   7  11


In [5]:
print(df_1.axes)

[Index(['r0', 'r1', 'r2'], dtype='object'), Index(['c0', 'c1', 'c2', 'c3'], dtype='object')]


In [6]:
print(df_1.dtypes)

c0    int32
c1    int32
c2    int32
c3    int32
dtype: object


In [7]:
print(df_1.size)

12


In [8]:
print(type(df_1))

<class 'pandas.core.frame.DataFrame'>


In [9]:
print(df_1.values)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [10]:
print(type(df_1.values))

<class 'numpy.ndarray'>


In [11]:
df_2=df({
    'class_1':['a','a','b','b','c'],
    'var_1':np.arange(5),
    'var_2':np.random.randn(5)}, 
    index=['r0','r1','r2','r3','r4'])

In [12]:
print(df_2)

   class_1  var_1     var_2
r0       a      0  0.384554
r1       a      1 -1.313508
r2       b      2 -0.063281
r3       b      3  3.013917
r4       c      4 -0.326598


In [13]:
print(df_2.index)

Index(['r0', 'r1', 'r2', 'r3', 'r4'], dtype='object')


In [19]:
print(df_2.iloc[2:])

   class_1  var_1     var_2
r2       b      2 -0.063281
r3       b      3  3.013917
r4       c      4 -0.326598


In [20]:
print(df_2.iloc[2])

class_1            b
var_1              2
var_2     -0.0632805
Name: r2, dtype: object


In [21]:
print(df_2.head(3))

   class_1  var_1     var_2
r0       a      0  0.384554
r1       a      1 -1.313508
r2       b      2 -0.063281


In [22]:
print(df_2.tail(3))

   class_1  var_1     var_2
r2       b      2 -0.063281
r3       b      3  3.013917
r4       c      4 -0.326598


In [23]:
print(df_2.columns)

Index(['class_1', 'var_1', 'var_2'], dtype='object')


In [24]:
print(df_2['class_1'])

r0    a
r1    a
r2    b
r3    b
r4    c
Name: class_1, dtype: object


In [25]:
print(df_2[['class_1','var_2']])

   class_1     var_2
r0       a  0.384554
r1       a -1.313508
r2       b -0.063281
r3       b  3.013917
r4       c -0.326598


==========================================================

In [31]:
idx=['r0','r1','r2','r3','r4']
df_1=df({'c1':np.arange(5),
         'c2': np.random.randn(5)},
        index=idx)
print(df_1)

    c1        c2
r0   0  0.742612
r1   1  0.931597
r2   2  0.848705
r3   3 -0.954768
r4   4 -0.039375


In [32]:
new_idx=['r0','r1','r2','r5','r6']
df_1=df_1.reindex(new_idx)
print(df_1)

     c1        c2
r0  0.0  0.742612
r1  1.0  0.931597
r2  2.0  0.848705
r5  NaN       NaN
r6  NaN       NaN


In [37]:
df_1=df_1.reindex(new_idx,fill_value='missing')
print(df_1)

     c1        c2
r0  0.0  0.742612
r1  1.0  0.931597
r2  2.0  0.848705
r5  NaN       NaN
r6  NaN       NaN


=========================================================

In [35]:
print(pd.date_range("2018-9-10", "2018-9-30", freq='B'))

DatetimeIndex(['2018-09-10', '2018-09-11', '2018-09-12', '2018-09-13',
               '2018-09-14', '2018-09-17', '2018-09-18', '2018-09-19',
               '2018-09-20', '2018-09-21', '2018-09-24', '2018-09-25',
               '2018-09-26', '2018-09-27', '2018-09-28'],
              dtype='datetime64[ns]', freq='B')


In [36]:
date_idx=pd.date_range("09/10/2018", periods=10, freq='D')
print(date_idx)

DatetimeIndex(['2018-09-10', '2018-09-11', '2018-09-12', '2018-09-13',
               '2018-09-14', '2018-09-15', '2018-09-16', '2018-09-17',
               '2018-09-18', '2018-09-19'],
              dtype='datetime64[ns]', freq='D')


In [38]:
df_2=df({"c1":[10,20,30,40,50,10,20,30,40,50]},index=date_idx)
print(df_2)

            c1
2018-09-10  10
2018-09-11  20
2018-09-12  30
2018-09-13  40
2018-09-14  50
2018-09-15  10
2018-09-16  20
2018-09-17  30
2018-09-18  40
2018-09-19  50


In [39]:
date_idx2=pd.date_range("09/05/2018", periods=20, freq='D')
print(date_idx2)

DatetimeIndex(['2018-09-05', '2018-09-06', '2018-09-07', '2018-09-08',
               '2018-09-09', '2018-09-10', '2018-09-11', '2018-09-12',
               '2018-09-13', '2018-09-14', '2018-09-15', '2018-09-16',
               '2018-09-17', '2018-09-18', '2018-09-19', '2018-09-20',
               '2018-09-21', '2018-09-22', '2018-09-23', '2018-09-24'],
              dtype='datetime64[ns]', freq='D')


In [40]:
df_2=df_2.reindex(date_idx2)
print(df_2)

              c1
2018-09-05   NaN
2018-09-06   NaN
2018-09-07   NaN
2018-09-08   NaN
2018-09-09   NaN
2018-09-10  10.0
2018-09-11  20.0
2018-09-12  30.0
2018-09-13  40.0
2018-09-14  50.0
2018-09-15  10.0
2018-09-16  20.0
2018-09-17  30.0
2018-09-18  40.0
2018-09-19  50.0
2018-09-20   NaN
2018-09-21   NaN
2018-09-22   NaN
2018-09-23   NaN
2018-09-24   NaN


In [41]:
df_2=df_2.reindex(date_idx2, method='bfill')
print(df_2)

              c1
2018-09-05   NaN
2018-09-06   NaN
2018-09-07   NaN
2018-09-08   NaN
2018-09-09   NaN
2018-09-10  10.0
2018-09-11  20.0
2018-09-12  30.0
2018-09-13  40.0
2018-09-14  50.0
2018-09-15  10.0
2018-09-16  20.0
2018-09-17  30.0
2018-09-18  40.0
2018-09-19  50.0
2018-09-20   NaN
2018-09-21   NaN
2018-09-22   NaN
2018-09-23   NaN
2018-09-24   NaN
