# Functions of Numpy

In [ ]:
import numpy as np

In [12]:
list1=[1,2,3,4]
print("list : ", list1)

list :  [1, 2, 3, 4]


In [13]:
print(type(list1))

<class 'list'>


In [11]:
a=np.array(list1)
print("array : ",a)

array :  [1 2 3 4]


In [14]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
print(a.shape)

(4,)


In [5]:
print(a[2])

3


=======================================================

In [7]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
print(b.shape)

(2, 3)


In [9]:
print(b[0][0])

1


In [10]:
print(type(b))

<class 'numpy.ndarray'>


=======================================================

**벡터화 연산**

In [15]:
a=np.array([1,2,3])
b=np.array([10,20,10])

In [16]:
print(a*2+b)

[12 24 16]


In [17]:
print(a==2)

[False  True False]


In [18]:
print(b>10)

[False  True False]


In [19]:
print((a==2)&(b>10))

[False  True False]


In [20]:
print(a.shape)

(3,)


In [21]:
print(a.ndim)

1


In [22]:
print(a.dtype)

int32


=======================================================

In [23]:
a=np.zeros(4)

In [24]:
print(a)

[0. 0. 0. 0.]


In [25]:
print(type(a))

<class 'numpy.ndarray'>


In [29]:
print(a.dtype)

float64


=======================================================

In [38]:
a=np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [37]:
a=np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [39]:
a=np.full((2,3),5)
print(a)

[[5 5 5]
 [5 5 5]]


In [40]:
a=np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


=======================================================

In [43]:
print(np.array(range(20)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [44]:
print(np.array(range(20)).reshape(4,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [47]:
c=np.array(range(20)).reshape(4,5)

In [48]:
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [46]:
print(len(c))

4


In [49]:
print(c.ndim)

2


In [50]:
print(c.shape)

(4, 5)


In [51]:
print(c>10)

[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]]


In [52]:
print(c[c>10])

[11 12 13 14 15 16 17 18 19]


In [54]:
c[c>10]=99
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 99 99 99 99]
 [99 99 99 99 99]]


=======================================================

In [55]:
arr=np.arange(0,3*2*4)

In [56]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [57]:
print(len(arr))

24


In [58]:
v=arr.reshape([3,2,4])

In [59]:
print(v)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [60]:
print(len(v))

3


In [61]:
print(len(v[0]))

2


In [62]:
print(len(v[0][0]))

4


=======================================================