# Functions of Numpy 3

In [3]:
import numpy as np

**axis() : 축지정**

In [4]:
a=np.arange(1,10).reshape(3,3)

In [5]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
print(np.sum(a))

45


In [7]:
print(np.sum(a,axis=1))

[ 6 15 24]


In [8]:
print(np.max(a))

9


In [9]:
print(np.max(a,axis=0))

[7 8 9]


In [10]:
print(np.max(a,axis=1))

[3 6 9]


**cumsum() : 누적합계**

In [11]:
print(np.cumsum(a))

[ 1  3  6 10 15 21 28 36 45]


In [12]:
print(np.cumsum(a, axis=0))

[[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]


In [13]:
print(np.cumsum(a,axis=1))

[[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


**median() : 중앙값**

In [14]:
print(np.median(a))

5.0


In [15]:
print(np.median(a,axis=0))

[4. 5. 6.]


In [16]:
print(np.median(a,axis=1))

[2. 5. 8.]


In [18]:
a=np.arange(1,5).reshape(2,2)
print(np.median(a))

2.5


**std() : 표준편차**

In [19]:
print(np.std(a))

1.118033988749895


In [20]:
print(np.std(a,axis=0))

[1. 1.]


In [21]:
print(np.std(a,axis=1))

[0.5 0.5]


**브로드캐스팅**

In [27]:
a=np.arange(1,25).reshape(4,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [26]:
print(a+100)

[[101 102 103 104 105 106]
 [107 108 109 110 111 112]
 [113 114 115 116 117 118]
 [119 120 121 122 123 124]]


In [24]:
new_arr=np.full_like(a,10)
print(a+new_arr)

[[11 12 13 14 15 16]
 [17 18 19 20 21 22]
 [23 24 25 26 27 28]
 [29 30 31 32 33 34]]


In [29]:
a=np.arange(5).reshape((1,5))
print(a)
b=np.arange(5).reshape((5,1))
print(b)
print(a+b)

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


**배열 복사**

In [30]:
a=np.random.randint(0,9,(3,3))
print(a)

[[4 3 8]
 [4 1 0]
 [4 7 3]]


In [31]:
a1=np.copy(a)
a1[:,0]=99
print(a1)

[[99  3  8]
 [99  1  0]
 [99  7  3]]


In [35]:
print(a)

[[4 3 8]
 [4 1 0]
 [4 7 3]]


**정렬**

In [33]:
uns=np.random.random((3,3))
print(uns)

[[0.57897228 0.49993505 0.66878602]
 [0.73645014 0.64238096 0.51065088]
 [0.02112619 0.98307037 0.35451859]]


In [34]:
uns1=uns
uns2=uns
uns3=uns
uns1.sort(axis=0)
print(uns1)

[[0.02112619 0.49993505 0.35451859]
 [0.57897228 0.64238096 0.51065088]
 [0.73645014 0.98307037 0.66878602]]


In [36]:
a=np.array([40,30,10,20])
j=np.argsort(a)
print(j)

[2 3 1 0]


In [37]:
print(a[j])

[10 20 30 40]


In [38]:
print(np.sort(a))

[10 20 30 40]


In [39]:
np.sort(a,axis=0)[::-1]

array([40, 30, 20, 10])

In [40]:
x=np.array([14,23,21,25,22,26,20])
print(np.sort(x))

[14 20 21 22 23 25 26]


In [41]:
print(x)

[14 23 21 25 22 26 20]


In [44]:
x.sort()
print(x)

[14 20 21 22 23 25 26]


In [46]:
xrev=np.sort(x)[::-1]
print(xrev)

[26 25 23 22 21 20 14]


In [47]:
print(np.argsort(-x))

[6 5 4 3 2 1 0]


In [48]:
print(x[np.argsort(-x)])

[26 25 23 22 21 20 14]


**텐서(tensor)**

In [49]:
arr=np.arange(0,2*3*4)
v=arr.reshape([2,3,4])
print(v)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [50]:
print(v.sum())

276


In [51]:
print(v.ndim)

3


In [52]:
res1=v.sum(axis=0)
print(res1.shape)

(3, 4)


In [53]:
res2=v.sum(axis=1)
print(res2.shape)

(2, 4)


In [54]:
res3=v.sum(axis=2)
print(res3.shape)

(2, 3)
