# Functions of Numpy 5

In [6]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
import matplotlib.pyplot as plt
import random

In [2]:
num=np.array(['3.14','-2.7','30'],dtype=np.string_)
num=num.astype(float).astype(int)
print(num)

[ 3 -2 30]


In [3]:
arr=np.arange(32).reshape((8,4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [4]:
print(arr[[1,5,7,2],[0,3,1,2]])

[ 4 23 29 10]


In [5]:
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [7]:
position=0
walk=[]
steps=1000
for i in range(steps):
    step = 1 if random.randint(0,1) else -1
    position+=step
    walk.append(position)

In [8]:
print("position : ",position)

position :  22


In [12]:
print("walk : ",walk)

walk :  [1, 2, 1, 0, -1, 0, 1, 2, 1, 2, 3, 2, 3, 2, 3, 2, 3, 4, 5, 4, 3, 4, 5, 6, 5, 6, 7, 6, 5, 6, 7, 8, 7, 8, 7, 6, 7, 6, 7, 8, 7, 8, 7, 8, 7, 6, 5, 6, 7, 6, 5, 4, 3, 2, 3, 4, 3, 4, 5, 4, 5, 6, 5, 6, 5, 6, 7, 8, 7, 6, 5, 6, 7, 8, 7, 8, 9, 8, 9, 8, 9, 10, 9, 10, 9, 8, 9, 10, 9, 10, 11, 10, 11, 10, 9, 10, 11, 10, 11, 12, 13, 12, 13, 12, 11, 12, 11, 10, 9, 10, 11, 12, 13, 14, 15, 16, 15, 14, 13, 14, 15, 16, 17, 16, 15, 16, 17, 16, 15, 16, 15, 16, 15, 16, 17, 16, 17, 18, 17, 18, 17, 16, 17, 18, 19, 18, 19, 18, 19, 20, 21, 20, 19, 18, 19, 20, 19, 18, 17, 18, 17, 16, 17, 16, 15, 16, 17, 18, 19, 18, 19, 20, 19, 18, 17, 16, 17, 18, 19, 18, 17, 18, 19, 18, 17, 18, 17, 16, 15, 14, 15, 16, 17, 18, 17, 16, 15, 16, 17, 16, 17, 18, 19, 20, 19, 20, 21, 22, 21, 22, 23, 22, 21, 22, 23, 24, 23, 22, 23, 22, 23, 24, 25, 24, 25, 26, 25, 26, 25, 24, 25, 24, 25, 24, 23, 24, 25, 26, 25, 24, 23, 22, 23, 24, 25, 26, 25, 24, 23, 24, 25, 26, 25, 24, 23, 24, 23, 22, 23, 24, 25, 24, 25, 26, 25, 24, 23, 22, 21, 20

In [10]:
print(min(walk))

-1


In [13]:
print(max(walk))

36


In [14]:
print(np.abs(walk))

[ 1  2  1  0  1  0  1  2  1  2  3  2  3  2  3  2  3  4  5  4  3  4  5  6
  5  6  7  6  5  6  7  8  7  8  7  6  7  6  7  8  7  8  7  8  7  6  5  6
  7  6  5  4  3  2  3  4  3  4  5  4  5  6  5  6  5  6  7  8  7  6  5  6
  7  8  7  8  9  8  9  8  9 10  9 10  9  8  9 10  9 10 11 10 11 10  9 10
 11 10 11 12 13 12 13 12 11 12 11 10  9 10 11 12 13 14 15 16 15 14 13 14
 15 16 17 16 15 16 17 16 15 16 15 16 15 16 17 16 17 18 17 18 17 16 17 18
 19 18 19 18 19 20 21 20 19 18 19 20 19 18 17 18 17 16 17 16 15 16 17 18
 19 18 19 20 19 18 17 16 17 18 19 18 17 18 19 18 17 18 17 16 15 14 15 16
 17 18 17 16 15 16 17 16 17 18 19 20 19 20 21 22 21 22 23 22 21 22 23 24
 23 22 23 22 23 24 25 24 25 26 25 26 25 24 25 24 25 24 23 24 25 26 25 24
 23 22 23 24 25 26 25 24 23 24 25 26 25 24 23 24 23 22 23 24 25 24 25 26
 25 24 23 22 21 20 21 20 19 20 19 20 19 18 17 16 15 14 15 14 15 16 17 16
 15 16 17 18 19 18 17 16 15 16 17 18 17 16 15 14 13 14 13 12 11 10 11 10
  9  8  7  6  5  6  7  8  7  8  7  8  9 10 11 12 13

=====================================================================================

In [15]:
obj=Series([1,2,-3,4])
print(obj)

0    1
1    2
2   -3
3    4
dtype: int64


In [16]:
print(obj.values)

[ 1  2 -3  4]


In [17]:
print(obj.index)

RangeIndex(start=0, stop=4, step=1)


In [18]:
obj=Series([1,2,-3,4], index=['x','y','z','k'])
print(obj)

x    1
y    2
z   -3
k    4
dtype: int64


In [19]:
print(obj['y'])

2


In [20]:
obj['x']=10
print(obj)

x    10
y     2
z    -3
k     4
dtype: int64


In [21]:
print(obj[['x','y','z']])

x    10
y     2
z    -3
dtype: int64


In [22]:
print(obj>0)

x     True
y     True
z    False
k     True
dtype: bool


In [23]:
print(obj[obj>0])

x    10
y     2
k     4
dtype: int64


In [24]:
print(obj*2)

x    20
y     4
z    -6
k     8
dtype: int64


In [25]:
print(np.exp(obj))

x    22026.465795
y        7.389056
z        0.049787
k       54.598150
dtype: float64


In [26]:
print(obj)

x    10
y     2
z    -3
k     4
dtype: int64


In [27]:
print('a' in obj)

False


In [28]:
print('x' in obj)

True


==================================================================================

In [31]:
sdata={'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3=Series(sdata)
print(obj3)

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64


In [32]:
print(type(obj3))

<class 'pandas.core.series.Series'>


In [33]:
states = ['California','Ohio','Oregon','Texas']
obj99=Series(states)
print(obj99)

0    California
1          Ohio
2        Oregon
3         Texas
dtype: object


In [34]:
obj4=Series(sdata, index=states)
print(obj4)

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64


In [35]:
print(pd.isnull(obj4))

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool


In [36]:
print(obj3+obj4)

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64


In [37]:
obj4.name='population'
obj.index.name='stae'
print(obj4)

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64


In [39]:
obj4.index=['w','x','y','z']
print(obj4)

w        NaN
x    35000.0
y    16000.0
z    71000.0
Name: population, dtype: float64


==================================================================================

In [40]:
data={
    'state':['Ohio', 'Ohio', 'Ohio', 'Ohio', 'Nevead'],
    'year':[2000, 2001, 2002, 2001, 2002],
    'pop':[1.5, 1.7, 3.6, 2.4, 2.9]}
frame = DataFrame(data)
print(frame)

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3    Ohio  2001  2.4
4  Nevead  2002  2.9


In [41]:
frame=DataFrame(data, columns=['year', 'state', 'pop'])
print(frame)

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001    Ohio  2.4
4  2002  Nevead  2.9


In [42]:
frame2=DataFrame(data, 
    columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five'])
print(frame2)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001    Ohio  2.4  NaN
five   2002  Nevead  2.9  NaN


In [43]:
print(frame2['state'])

one        Ohio
two        Ohio
three      Ohio
four       Ohio
five     Nevead
Name: state, dtype: object


In [44]:
print(frame2['year'])

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64


In [49]:
print(frame2.loc['three'])

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object


In [51]:
print(frame2.loc[['three', 'five']])

       year   state  pop debt
three  2002    Ohio  3.6  NaN
five   2002  Nevead  2.9  NaN


In [52]:
frame2['debt']=16.5
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001    Ohio  2.4  16.5
five   2002  Nevead  2.9  16.5


In [53]:
frame2['debt']=np.arange(5)
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001    Ohio  2.4     3
five   2002  Nevead  2.9     4


In [54]:
val=Series([-1.2, -1.5, -1.7],
           index=['two', 'four', 'five'])
frame2['debt']=val
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001    Ohio  2.4  -1.5
five   2002  Nevead  2.9  -1.7


In [55]:
frame2['eastern']=frame2.state=='Ohio'
print(frame2)

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001    Ohio  2.4  -1.5     True
five   2002  Nevead  2.9  -1.7    False


In [56]:
del frame2['eastern']
print(frame2)

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001    Ohio  2.4  -1.5
five   2002  Nevead  2.9  -1.7


In [57]:
print(frame2.columns)

Index(['year', 'state', 'pop', 'debt'], dtype='object')


In [58]:
print(frame2.index)

Index(['one', 'two', 'three', 'four', 'five'], dtype='object')


In [59]:
pop={'Nevada':{2001:2.4, 2002:2.9},
     'Ohio': {2000:1.5, 2001:2.7, 2002: 3.6}}
frame3=DataFrame(pop)
print(frame3)

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   2.7
2002     2.9   3.6


In [60]:
print(frame3.T)

        2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   2.7   3.6


In [61]:
frame4=DataFrame(frame3, index=['2001', '2002', '2003'])
print(frame4)

      Nevada  Ohio
2001     NaN   NaN
2002     NaN   NaN
2003     NaN   NaN


In [62]:
pdata={'Ohio':frame3['Ohio'][:-1],
       'Nevada': frame3['Nevada'][:2]}
frame5=DataFrame(pdata)
print(frame5)

      Ohio  Nevada
2000   1.5     NaN
2001   2.7     2.4
