# Functions of Numpy 4

In [1]:
import numpy as np

In [4]:
a1=np.arange(24)
print(a1)
a2=np.arange(24).reshape((4,6))
print(a2)
a3=np.arange(24).reshape((2,4,3))
print(a3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [7]:
a1[5]=1000
a2[0,1]=1000
a3[1,0,1]=1000
print(a1)
print(a2)
print(a3)

[   0    1    2    3    4 1000    6    7    8    9   10   11   12   13
   14   15   16   17   18   19   20   21   22   23]
[[   0 1000    2    3    4    5]
 [   6    7    8    9   10   11]
 [  12   13   14   15   16   17]
 [  18   19   20   21   22   23]]
[[[   0    1    2]
  [   3    4    5]
  [   6    7    8]
  [   9   10   11]]

 [[  12 1000   14]
  [  15   16   17]
  [  18   19   20]
  [  21   22   23]]]


In [8]:
print(a2[1:3,1:5])

[[ 7  8  9 10]
 [13 14 15 16]]


In [9]:
print(a2[1:-1, 1:-1])

[[ 7  8  9 10]
 [13 14 15 16]]


In [10]:
print(a2[:,1:3])

[[1000    2]
 [   7    8]
 [  13   14]
 [  19   20]]


In [11]:
a2[:,1:3]=99
print(a2)

[[ 0 99 99  3  4  5]
 [ 6 99 99  9 10 11]
 [12 99 99 15 16 17]
 [18 99 99 21 22 23]]


In [12]:
a1=np.arange(1,25).reshape(4,6)
even_a=a1%2==0
print(a1[even_a])

[ 2  4  6  8 10 12 14 16 18 20 22 24]


**ravel()**

In [14]:
a=np.random.randint(1,10,(2,3))
print(a)

[[8 1 8]
 [2 6 9]]


In [15]:
print(a.ravel())

[8 1 8 2 6 9]


In [16]:
print(a)

[[8 1 8]
 [2 6 9]]


In [17]:
b=a.ravel()
print(b)

[8 1 8 2 6 9]


**팬시 인덱싱**

In [18]:
a=np.arange(1,25).reshape((4,6))
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [19]:
print([a[0,0],a[1,1],a[2,2],a[3,3]])

[1, 8, 15, 22]


In [20]:
print(a[[0,1,2,3],[0,1,2,3]])

[ 1  8 15 22]


In [21]:
print(a[:,[1,2]])

[[ 2  3]
 [ 8  9]
 [14 15]
 [20 21]]


**배열변경**

In [22]:
a=np.random.randint(1,10,(2,6))
print(a)

[[6 7 7 8 8 1]
 [2 7 8 4 2 5]]


In [24]:
a.resize((3,3))
print(a)

[[6 7 7]
 [8 8 1]
 [2 7 8]]


In [52]:
a=np.arange(1,10).reshape(3,3)
b=np.arange(10,19).reshape(3,3)
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


**배열 추가**

In [30]:
res=np.append(a,b)
print(res)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [26]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
res=np.append(a,b,axis=0)
print(res)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [53]:
a=np.arange(1,10).reshape(3,3)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**배열 삽입**

In [36]:
a=np.arange(1,10).reshape(3,3)
a=np.insert(a,1,99)
print(a)

[ 1 99  2  3  4  5  6  7  8  9]


In [39]:
a=np.arange(1,10).reshape(3,3)
a=np.insert(a,1,99, axis=0)
print(a)

[[ 1  2  3]
 [99 99 99]
 [ 4  5  6]
 [ 7  8  9]]


In [54]:
a=np.arange(1,10).reshape(3,3)
a=np.insert(a,1,99, axis=1)
print(a)

[[ 1 99  2  3]
 [ 4 99  5  6]
 [ 7 99  8  9]]


**배열 삭제**

In [40]:
a=np.arange(1,10).reshape(3,3)
print(np.delete(a, 1))

[1 3 4 5 6 7 8 9]


In [41]:
a=np.arange(1,10).reshape(3,3)
print(np.delete(a, 1, axis=0))

[[1 2 3]
 [7 8 9]]


In [55]:
a=np.arange(1,10).reshape(3,3)
print(np.delete(a, 1,axis=1))

[[1 3]
 [4 6]
 [7 9]]


**배열 결합**

In [43]:
a=np.arange(1,7).reshape((2,3))
print(a)

[[1 2 3]
 [4 5 6]]


In [44]:
b=np.arange(7,13).reshape((2,3))
print(b)

[[ 7  8  9]
 [10 11 12]]


In [45]:
res=np.concatenate((a,b),axis=0)
print(res)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [46]:
res=np.concatenate((a,b),axis=1)
print(res)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [56]:
a=np.arange(1,7).reshape((2,3))
b=np.arange(7,13).reshape((2,3))
print(np.vstack((a,b,a,b)))
print(np.hstack((a,b,a,b)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9  1  2  3  7  8  9]
 [ 4  5  6 10 11 12  4  5  6 10 11 12]]


**배열 분리** 

In [49]:
a=np.arange(1,25).reshape(4,6)
print(a)
res=np.hsplit(a,3)
print(res)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[array([[ 1,  2],
       [ 7,  8],
       [13, 14],
       [19, 20]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16],
       [21, 22]]), array([[ 5,  6],
       [11, 12],
       [17, 18],
       [23, 24]])]


In [51]:
a=np.arange(1,25).reshape(4,6)
print(a)
res=np.vsplit(a,2)
print(res)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
[array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]]), array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])]


**행렬과 벡터**

In [59]:
x=np.array([[1,2],[3,4]])
print(x)
y=np.array([[5,6],[7,8]])
print(y)
v=np.array([9,10])
print(v)
w=np.array([11,12])
print(w)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[ 9 10]
[11 12]


In [58]:
print(np.dot(v,w))

219


In [60]:
print(x.dot(v))

[29 67]


In [61]:
print(x.T)

[[1 3]
 [2 4]]


In [62]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v=np.array([1,0,1])
y=np.empty_like(x)

In [63]:
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [64]:
for i in range(4):
    y[i,:]=x[i,:]+v
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [66]:
v=np.array([1,0,1])
print(v)

[1 0 1]


In [67]:
vv=np.tile(v,(4,1))
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [69]:
a=np.array([[1,2],[4,5]])
print(a)

[[1 2]
 [4 5]]


In [70]:
s=np.max(np.prod(a,axis=1))
print(s)

20


In [71]:
data=[[828.659973,833.450012,828.349976,1247700,831.659973],
[823.02002,828.070007,821.655029,1597800,828.070007],
[819.929993,824.400024,818.97998,1281700,824.159973],
[819.359985,823,818.469971,1304000,818.97998],
[819,823,816,1053600,820.450012],
[816,820.958984,815.48999,1198100,819.23999],
[811.700012,815.25,809.780029,1129100,813.669983],
[809.51001,810.659973,804.539978,989700,809.559998]]

In [72]:
data=np.array(data)
print(data)

[[8.28659973e+02 8.33450012e+02 8.28349976e+02 1.24770000e+06
  8.31659973e+02]
 [8.23020020e+02 8.28070007e+02 8.21655029e+02 1.59780000e+06
  8.28070007e+02]
 [8.19929993e+02 8.24400024e+02 8.18979980e+02 1.28170000e+06
  8.24159973e+02]
 [8.19359985e+02 8.23000000e+02 8.18469971e+02 1.30400000e+06
  8.18979980e+02]
 [8.19000000e+02 8.23000000e+02 8.16000000e+02 1.05360000e+06
  8.20450012e+02]
 [8.16000000e+02 8.20958984e+02 8.15489990e+02 1.19810000e+06
  8.19239990e+02]
 [8.11700012e+02 8.15250000e+02 8.09780029e+02 1.12910000e+06
  8.13669983e+02]
 [8.09510010e+02 8.10659973e+02 8.04539978e+02 9.89700000e+05
  8.09559998e+02]]


In [74]:
print(data.shape)

(8, 5)


In [75]:
data=np.transpose(data)
print(data)

[[8.28659973e+02 8.23020020e+02 8.19929993e+02 8.19359985e+02
  8.19000000e+02 8.16000000e+02 8.11700012e+02 8.09510010e+02]
 [8.33450012e+02 8.28070007e+02 8.24400024e+02 8.23000000e+02
  8.23000000e+02 8.20958984e+02 8.15250000e+02 8.10659973e+02]
 [8.28349976e+02 8.21655029e+02 8.18979980e+02 8.18469971e+02
  8.16000000e+02 8.15489990e+02 8.09780029e+02 8.04539978e+02]
 [1.24770000e+06 1.59780000e+06 1.28170000e+06 1.30400000e+06
  1.05360000e+06 1.19810000e+06 1.12910000e+06 9.89700000e+05]
 [8.31659973e+02 8.28070007e+02 8.24159973e+02 8.18979980e+02
  8.20450012e+02 8.19239990e+02 8.13669983e+02 8.09559998e+02]]


In [76]:
print(data.shape)

(5, 8)


**다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 
영어 성적을 기준으로 각 열(column)을 재정렬하라.**

In [80]:
score=np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])

In [82]:
score_eng=np.argsort(score[1])[::-1]
print(score[:,score_eng])

[[  3   2   4   1]
 [100  99  71  46]
 [ 90  59 100  81]]


**실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.**

In [84]:
data=np.random.randint(1,100,(5,6))
print(data)

[[13 86 25 77 40 25]
 [22 25 94 91 12  3]
 [34 17 73 96 20 71]
 [25 79 40 31  2 58]
 [10  9 56 62 16  1]]


**1.전체의 최댓값**

In [87]:
print(np.max(data))

96


**2.각 행의 합**

In [93]:
print(np.sum(data,axis=1))

[266 247 311 235 154]


**3.각 열의 평균**

In [94]:
print(np.mean(data,axis=0))

[20.8 43.2 57.6 71.4 18.  31.6]
