# Logistic Classification

In [15]:
import numpy as np
import tensorflow as tf
import math

In [16]:
xx = [[1,1,1,1,1,1],
      [2,3,3,5,7,2],
      [1,2,5,5,5,5]]
yy = np.array([0,0,0,1,1,1])
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
w = tf.Variable(tf.random_uniform([1,3], -1, 1))
z = tf.matmul(w,x)

# hf = 1 / (1 + tf.exp(-z))
# hf = tf.div(1, 1 + tf.exp(-z))
hf = tf.nn.sigmoid(z)
cost= -tf.reduce_mean(y*tf.log(hf)+(1-y)*tf.log(1-hf))
sess = tf.Session()
sess.run(tf.global_variables_initializer())

optimizer = tf.train.GradientDescentOptimizer(0.02)
train = optimizer.minimize(cost)

for i in range(2001) :
    sess.run(train, feed_dict = {x : xx, y : yy})
    if i % 100 == 0 :
        print(i, sess.run(cost, feed_dict={x : xx, y : yy}))

print("="*50)

xx = [[1, 1],
      [3, 7],
      [8, 2]]
print(sess.run(hf, feed_dict={x : xx}))

yhat = sess.run(hf, feed_dict={x : xx})
print(yhat>0.5)
print(sess.run(w))

0 1.2962648
100 0.6974108
200 0.6460249
300 0.6129492
400 0.5873954
500 0.56579274
600 0.54693824
700 0.5302945
800 0.5155216
900 0.50235754
1000 0.49058497
1100 0.48002002
1200 0.4705062
1300 0.46191016
1400 0.45411777
1500 0.44703153
1600 0.440568
1700 0.43465516
1800 0.42923078
1900 0.42424127
2000 0.41964015
[[0.903449 0.517566]]
[[ True  True]]
[[-2.7864199   0.25617135  0.5317568 ]]


In [17]:
def sigmoid(z):
    return 1/(1+math.e**-z)
ww = sess.run(w)
np.dot(ww,xx)

array([[2.23614872, 0.07029319]])

In [23]:
tf.set_random_seed(777)
xdata = [[1,2],
         [2,3],
         [3,1],
         [4,3],
         [5,3],
         [6,2]]
ydata = [[0],
         [0],
         [0],
         [1],
         [1],
         [1]]
x = tf.placeholder(tf.float32, shape = [None,2])
y = tf.placeholder(tf.float32, shape = [None,1])
w = tf.Variable(tf.random_normal([2,1]))
b = tf.Variable(tf.random_normal([1]))
hf = tf.sigmoid(tf.matmul(x,w)+b)
cost = -tf.reduce_mean(y*tf.log(hf)+(1-y)*tf.log(1-hf))
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

predicted = tf.cast(hf>0.5, dtype = tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, y), dtype = tf.float32))

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(1001):
        cv, _ = sess.run([cost, train], feed_dict={x:xdata, y:ydata})
        if step % 200 == 0:
            print(step, cv)
            
    hfv, pv, av = sess.run([hf, predicted, accuracy], feed_dict={x:xdata, y:ydata})
    print("\n예측값 : \n", hfv, "\n\n예측값(0/1) : \n", pv, "\n\n정확도 : \n", av)

0 3.671828
200 0.5614164
400 0.44796208
600 0.397891
800 0.370432
1000 0.35217366

예측값 : 
 [[0.18947262]
 [0.29536638]
 [0.5774632 ]
 [0.6675365 ]
 [0.81462187]
 [0.92149776]] 

예측값(0/1) : 
 [[0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]] 

정확도 : 
 0.8333333
