In [14]:
import numpy as np
import tensorflow as tf
import pandas as pd
tf.set_random_seed(777)

In [3]:
xy = np.loadtxt('DataSet/xy.txt', skiprows = 1)
print(xy)
print(xy.shape)
print(type(xy))

[[1. 1.]
 [2. 2.]
 [3. 3.]
 [4. 4.]
 [5. 5.]]
(5, 2)
<class 'numpy.ndarray'>


In [4]:
xxy = np.loadtxt('DataSet/xxy.csv', delimiter = ",")
print(xxy)

[[1. 1. 0. 1.]
 [1. 0. 2. 2.]
 [1. 3. 0. 3.]
 [1. 0. 4. 4.]
 [1. 5. 0. 5.]]


In [5]:
xxy2 = np.loadtxt('DataSet/xxy.csv', delimiter = ",", unpack=True)
print(xxy2)

[[1. 1. 1. 1. 1.]
 [1. 0. 3. 0. 5.]
 [0. 2. 0. 4. 0.]
 [1. 2. 3. 4. 5.]]


In [6]:
cars = np.loadtxt('DataSet/cars.csv', delimiter = ",")
print(cars.shape)

xx, yy = [], []
print(cars[1])

(50, 2)
[ 4. 10.]


In [7]:
for i in range(len(cars)) :
    item = cars[i]
    xx.append(item[0])
    yy.append(item[1])
print(xx)
print("="*50)
print(yy)


# for row in cars :
#     xx.append(row[0])
#     yy.append(row[1])
# print(xx)
# print("="*50)
# print(yy)


# for speed, distance in cars :
#     xx.append(speed)
#     yy.append(distance)
# print(xx)
# print("="*50)
# print(yy)

[4.0, 4.0, 7.0, 7.0, 8.0, 9.0, 10.0, 10.0, 10.0, 11.0, 11.0, 12.0, 12.0, 12.0, 12.0, 13.0, 13.0, 13.0, 13.0, 14.0, 14.0, 14.0, 14.0, 15.0, 15.0, 15.0, 16.0, 16.0, 17.0, 17.0, 17.0, 18.0, 18.0, 18.0, 18.0, 19.0, 19.0, 19.0, 20.0, 20.0, 20.0, 20.0, 20.0, 22.0, 23.0, 24.0, 24.0, 24.0, 24.0, 25.0]
[2.0, 10.0, 4.0, 22.0, 16.0, 10.0, 18.0, 26.0, 34.0, 17.0, 28.0, 14.0, 20.0, 24.0, 28.0, 26.0, 34.0, 34.0, 46.0, 26.0, 36.0, 60.0, 80.0, 20.0, 26.0, 54.0, 32.0, 40.0, 32.0, 40.0, 50.0, 42.0, 56.0, 76.0, 84.0, 36.0, 46.0, 68.0, 32.0, 48.0, 52.0, 56.0, 64.0, 66.0, 54.0, 70.0, 92.0, 93.0, 120.0, 85.0]


In [8]:
cars = np.loadtxt('DataSet/cars.csv', delimiter = ",", unpack=True)
print(cars.shape)
x=cars[0] # 스피드
y=cars[1] # 제동거리

cars = np.loadtxt('DataSet/cars.csv', delimiter = ",")
cars = cars.transpose()
print(cars.shape)

(2, 50)
(2, 50)


* * *

### 연습문제 - 속도가 30일때와 50일때의 제동거리를 예측하세요.

In [28]:
cars = pd.read_csv("DataSet/cars.csv", sep = ",")
cars.shape

(50, 2)

In [29]:
cars.head()

# "speed"  dist
0          4     2
1          4    10
2          7     4
3          7    22
4          8    16

In [30]:
cars.columns = ["speed", "dist"]
cars.head()

speed  dist
0      4     2
1      4    10
2      7     4
3      7    22
4      8    16

In [32]:
learningRate = 0.003
times = 5001

x_data = cars["speed"]
y_data = cars["dist"]

x = tf.placeholder(dtype = tf.float32, shape = [None])
y = tf.placeholder(dtype = tf.float32, shape = [None])
w = tf.Variable(tf.random_normal([1]))
b = tf.Variable(tf.random_normal([1]))
hf = w * x + b
cost = tf.reduce_mean(tf.square(hf - y))
train = tf.train.GradientDescentOptimizer(learning_rate=learningRate).minimize(cost)

with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    for step in range(times) :
        sess.run(train, feed_dict={x: x_data, y:y_data})
        if step%500 ==0:
            print(step, sess.run(cost, feed_dict={x: x_data, y:y_data}))

    print("===========모델 완성===========")
    cv, wv, bv = sess.run([cost, w, b], feed_dict={x: x_data, y:y_data})
    print("Cost : ", cv, "\n가중치 : ", wv, "\n편향 : ", bv)

    print("===========예측==============")
    print("속도가 30일때 예상되는 제동거리 : ", sess.run(hf, feed_dict={x:[30]}))
    print("속도가 50일때 예상되는 제동거리 : ", sess.run(hf, feed_dict={x:[50]}))

0 563.47107
500 244.11746
1000 236.24535
1500 232.0085
2000 229.72816
2500 228.50084
3000 227.84027
3500 227.48474
4000 227.29344
4500 227.19043
5000 227.13504
===========모델 완성===========
Cost :  227.13504 
가중치 :  [3.8864188] 
편향 :  [-16.78933]
===========예측==============
속도가 30일때 예상되는 제동거리 :  [99.80324]
속도가 50일때 예상되는 제동거리 :  [177.53162]
