In [68]:
import tensorflow as tf

In [69]:
hello = tf.constant('hello')
print(hello)  #tensor에 대한 정보 출력

Tensor("Const_65:0", shape=(), dtype=string)


In [70]:
sess = tf.Session()
print(sess)

In [71]:
sess.run(hello)  # 그래프 실행

b'hello'

In [72]:
str(sess.run(hello), encoding = 'utf-8')

'hello'

In [73]:
a = tf.constant(5, dtype = tf.float32)
b = tf.constant(10, dtype = tf.float32)
c = tf.constant(2, dtype = tf.float32)
d = a*b+c

In [77]:
sess = tf.Session()
res = sess.run(d)
print(res)

8


In [76]:
a = tf.constant(3)
print(a)

# sess=tf.Session()
# print(sess.run(a))
# sess.close() 세션종료->메모리 자원 반환

with tf.Session() as sess:  #sess라는 이름으로 세션 객체를 만들어라
    print(sess.run(a))
    print(a.eval())

Tensor("Const_71:0", shape=(), dtype=int32)
3
3


In [74]:
a = tf.constant(5)
b = tf.constant(3)
c = tf.multiply(a,b)   # c = a*b
d = tf.add(a,b)        # d = a+b
e = tf.add(c,d)        # e = c+d
sess = tf.Session()
print(sess.run(a))
print(sess.run(b))
print(sess.run(c))
print(sess.run(d))
print(sess.run(e))

5
3
15
8
23


In [75]:
inputdata = [1,2,3]
x = tf.placeholder(dtype = tf.int32) # 실행시점에 데이터가 전달
y = x*2
sess = tf.Session()
res = sess.run(y,feed_dict={x:inputdata})
print(res)

[2 4 6]


In [78]:
a = tf.placeholder(dtype = tf.float32)
b = tf.placeholder("float")
y = tf.multiply(a,b)
z = tf.add(y,y)

sess = tf.Session()
print(sess.run(y, feed_dict={a:3, b:2}))
print(sess.run(z, feed_dict={a:3, b:2}))

6.0
12.0


In [79]:
x = tf.constant(15)
y = tf.Variable(x+5)
sess = tf.Session()
init=tf.global_variables_initializer() 
sess.run(init)  # 변수 초기화(!)
print(sess.run(y))

20


In [80]:
inputdata = [1,2,3,4,5]
x = tf.placeholder(dtype = tf.float32)
w = tf.Variable(2, dtype = tf.float32)
y = tf.multiply(w,x) # y = w*x
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
print(sess.run(y, feed_dict={x:inputdata}))

[ 2.  4.  6.  8. 10.]


In [81]:
x = tf.linspace(-1.0, 1.0, 10)  # 구간 나누기 함수
sess = tf.Session()
print(sess.run(x))
sess.close()

[-1.         -0.7777778  -0.5555556  -0.3333333  -0.1111111   0.11111116
  0.33333337  0.5555556   0.7777778   1.        ]


In [86]:
a = tf.placeholder("float")
b = tf.placeholder("float")
y = tf.multiply(a,b)
z = tf.add(y,y)
with tf.Session() as sess :
    print(sess.run(z, feed_dict={a:4, b:4})) 

32.0


In [85]:
a = tf.placeholder("float")
b = tf.placeholder("float")
y = tf.multiply(a,b)
z = tf.add(y,y)
with tf.Session() as sess :
    print(sess.run(z, feed_dict={a:4, b:4, y:5})) #y값 우선

10.0


In [83]:
x = tf.constant([[1.0, 2.0, 3.0]])  #1행 3열
w = tf.constant([[2.0], [2.0], [2.0]]) #3행 1열
y = tf.matmul(w,x)
sess = tf.Session()
res = sess.run(y)
print(res)

[[2. 4. 6.]
 [2. 4. 6.]
 [2. 4. 6.]]


In [82]:
x = tf.constant([[1.0, 2.0, 3.0]])  #1행 3열
w = tf.constant([[2.0], [2.0], [2.0]]) #3행 1열
y = tf.matmul(x,w)
sess = tf.Session()
res = sess.run(y)
print(res)

[[12.]]


In [84]:
x = tf.Variable([[1.0, 2.0, 3.0]])  #1행 3열
w = tf.constant([[2.0], [2.0], [2.0]]) #3행 1열
y = tf.matmul(x,w)
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
res = sess.run(y)
print(res)

[[12.]]


In [88]:
input_data = [[1.0, 2.0, 3.0],[1.0, 2.0, 3.0],[2.0, 3.0, 4.0]] # 3행 3열
x = tf.placeholder(dtype = tf.float32, shape = [None,3])  # 행:?, 열:3 training data가 늘어날 수 있어서 행값에 None
w = tf.Variable([[2.0], [2.0], [2.0]]) # w의 초기값 : 2, 데이터타입 : float
y = tf.matmul(x,w)
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
res = sess.run(y, feed_dict={x:input_data})
print(res)

[[12.]
 [12.]
 [18.]]


In [87]:
input1 = tf.constant([3.0])
input2 = tf.constant([2.0])
input3 = tf.constant([5.0])
inter = tf.add(input2, input3)
mul = tf.multiply(input1, inter)
with tf.Session() as sess :
    res= sess.run([mul, inter]) #리스트로 반환(인덱스 선택 가능)
    mulres = sess.run(mul)
    mulinter = sess.run(inter)
print(res)
print(mulres)
print(mulinter)

[array([21.], dtype=float32), array([7.], dtype=float32)]
[21.]
[7.]
