In [19]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)

In [12]:
x1_data = [280, 310, 250, 270, 277] # 모의고사 1회
x2_data = [310, 300, 225, 267, 301] # 모의고사 2회
x3_data = [270, 325, 205, 290, 300] # 모의고사 3회
y_data = [299, 327, 240, 270, 290] # 수능점수

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name = 'w1')
w2 = tf.Variable(tf.random_normal([1]), name = 'w2')
w3 = tf.Variable(tf.random_normal([1]), name = 'w3')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
hf = x1*w1+x2*w2+x3*w3+b

cost = tf.reduce_mean(tf.square(hf-y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-6)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(5001):
    cv, hv, _ = sess.run([cost, hf, train], feed_dict = {x1 : x1_data, x2 : x2_data, x3 : x3_data, y : y_data})
    if step % 500 == 0 :
        print(step, "\tCost : ", cv, "\t예측 : ", hv)

0 	Cost :  308426.47 	예측 :  [-247.3937  -318.58078 -192.56052 -284.32596 -286.56387]
500 	Cost :  187.87674 	예측 :  [314.18002 303.6452  251.47011 266.48587 294.42624]
1000 	Cost :  119.53569 	예측 :  [309.38568 307.04846 248.19142 269.7542  294.95908]
1500 	Cost :  84.194016 	예측 :  [305.87494 309.52185 246.04485 272.09094 295.22565]
2000 	Cost :  65.67401 	예측 :  [303.29257 311.32666 244.6629  273.76596 295.3259 ]
2500 	Cost :  55.817577 	예측 :  [301.38403 312.64926 243.79355 274.97012 295.3261 ]
3000 	Cost :  50.478584 	예측 :  [299.96674 313.623   243.26453 275.8385  295.2696 ]
3500 	Cost :  47.53056 	예측 :  [298.90878 314.34314 242.9587  276.4668  295.1841 ]
4000 	Cost :  45.869083 	예측 :  [298.11505 314.8785  242.7969  276.9232  295.0871 ]
4500 	Cost :  44.913185 	예측 :  [297.5165  315.27844 242.72604 277.25592 294.98904]
5000 	Cost :  44.352093 	예측 :  [297.06277 315.5788  242.71083 277.4996  294.89603]


In [18]:
x_data = [[280, 310, 270],
         [310, 300, 325],
         [250, 225, 205],
         [270, 267, 290],
         [277, 301, 300]]

y_data = [[299], 
          [327], 
          [240], 
          [270], 
          [290]] # 수능점수

x = tf.placeholder(tf.float32, shape = [None, 3])
y = tf.placeholder(tf.float32, shape = [None, 1])
w = tf.Variable(tf.random_normal([3,1]), name = 'w')
b = tf.Variable(tf.random_normal([1]), name = 'bias')
hf = tf.matmul(x,w)+b

cost = tf.reduce_mean(tf.square(hf-y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-6)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for step in range(5001):
    cv, hv, _ = sess.run([cost, hf, train], feed_dict = {x : x_data, y : y_data})
    if step % 1000 == 0 :
        print(step, "\tCost : ", cv, "\n예측 : ", hv)

0 	Cost :  1440351.2 
예측 :  [[ -954.11774]
 [-1003.1735 ]
 [ -744.8593 ]
 [ -887.5029 ]
 [ -955.9254 ]]
1000 	Cost :  106.20602 
예측 :  [[284.20862]
 [324.54443]
 [235.45946]
 [285.9441 ]
 [295.6022 ]]
2000 	Cost :  60.03438 
예측 :  [[289.41815]
 [320.77997]
 [239.92427]
 [282.19208]
 [294.58463]]
3000 	Cost :  48.21305 
예측 :  [[292.16214]
 [318.82254]
 [241.93161]
 [280.29233]
 [294.21603]]
4000 	Cost :  45.068924 
예측 :  [[293.6312 ]
 [317.79016]
 [242.79578]
 [279.32205]
 [294.12097]]
5000 	Cost :  44.184937 
예측 :  [[294.43216]
 [317.2367 ]
 [243.14053]
 [278.82114]
 [294.1306 ]]


In [21]:
xy = np.loadtxt("DataSet/score.csv", delimiter = ",", dtype = np.float32)
print(xy)

[[ 80.  79.  77. 149.]
 [ 93.  88.  93. 185.]
 [ 89.  91.  90. 180.]
 [ 96.  98. 100. 196.]
 [ 73.  66.  70. 142.]
 [ 53.  46.  55. 101.]
 [ 69.  74.  77. 149.]
 [ 47.  56.  60. 115.]
 [ 87.  79.  90. 175.]
 [ 79.  70.  88. 164.]
 [ 69.  70.  73. 141.]
 [ 70.  65.  74. 141.]
 [ 93.  95.  91. 184.]
 [ 79.  80.  73. 152.]
 [ 70.  73.  78. 148.]
 [ 93.  89.  96. 192.]
 [ 78.  75.  68. 147.]
 [ 81.  90.  93. 183.]
 [ 88.  92.  86. 177.]
 [ 78.  83.  77. 159.]
 [ 82.  86.  90. 177.]
 [ 86.  82.  89. 175.]
 [ 78.  83.  85. 175.]
 [ 76.  83.  71. 149.]
 [ 96.  93.  95. 192.]]


In [22]:
xdata = xy[:, 0:-1]
print(xdata)

[[ 80.  79.  77.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]


In [23]:
ydata = xy[:, [-1]]
print(ydata)

[[149.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
