# Softmax classifier

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
xy = np.loadtxt('DataSet/softmax.txt', dtype = np.float32)
print(xy)

[[1. 2. 1. 0. 0. 1.]
 [1. 3. 2. 0. 0. 1.]
 [1. 3. 4. 0. 0. 1.]
 [1. 5. 5. 0. 1. 0.]
 [1. 7. 5. 0. 1. 0.]
 [1. 2. 5. 0. 1. 0.]
 [1. 6. 6. 1. 0. 0.]
 [1. 7. 7. 1. 0. 0.]]


In [3]:
xx = xy[:, :3]
y = xy[:, 3:]
print(xx)
print(y)

[[1. 2. 1.]
 [1. 3. 2.]
 [1. 3. 4.]
 [1. 5. 5.]
 [1. 7. 5.]
 [1. 2. 5.]
 [1. 6. 6.]
 [1. 7. 7.]]
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [6]:
x= tf.placeholder(tf.float32)
w = tf.Variable(tf.zeros([3,3])) # x 개수, y 개수
z = tf.matmul(x,w)
hf = tf.nn.softmax(z) # z값이 확률로 출력
cost = tf.reduce_mean(-tf.reduce_sum(y * tf.log(hf), axis=1)) 
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
for i in range(2001):
    sess.run(train, feed_dict = {x : xx})
    if i % 200 == 0 :
        print(sess.run(cost, feed_dict = {x:xx}))

1.0678048
0.6996808
0.5945788
0.53582877
0.49431214
0.4619158
0.4353428
0.4128906
0.3935346
0.37659502
0.36159125


In [9]:
# 예측값 적용
yhat = sess.run(hf, feed_dict = {x:[[1, 11, 7],
                                   [1, 3, 4]]})
print(yhat)

[[8.7813419e-01 1.2148806e-01 3.7768690e-04]
 [4.4764925e-02 4.4394752e-01 5.1128757e-01]]


In [12]:
# argmax로 인덱스 출력
grades = ['A', 'B', 'C']
yhat2 = sess.run(tf.argmax(yhat, axis = 1))
print(yhat2)

[0 2]


In [18]:
# 인덱스 값 출력
print(grades[yhat2[0]],grades[yhat2[1]])

A C


In [17]:
# numpy 이용
grades = np.array(['A', 'B', 'C'])
print(grades[yhat2])

['A' 'C']


* * *

In [20]:
import math
def softmax() :
    aa = math.e**2.0
    bb = math.e**1.0
    cc = math.e**0.1
    base = aa+bb+cc
    print(aa/base)
    print(bb/base)
    print(cc/base)
softmax()

0.6590011388859678
0.2424329707047139
0.09856589040931818


* * *

# Iiris data 

[문제]
120개의 트레이닝 데이터셋 모델 작성, 30개의 test 데이터셋으로 검증


In [35]:
def read_iris_sotfmax() :
    iris = np.loadtxt('DataSet/iris_softmax.csv', delimiter=',', dtype = np.float32)
    print("iris_shape",iris.shape)
    train_set = np.vstack((iris[:40],iris[50:90],iris[100:140]))
    print("train_set", train_set.shape)
    test_set = np.vstack((iris[40:50],iris[90:100],iris[140:]))
    print("test_set",test_set.shape)
    return train_set, test_set
train_set, test_set = read_iris_sotfmax()
xx = train_set[:,:-3]
print("xx",xx.shape)
y = train_set[:,-3:]
print("y",y.shape)

iris_shape (150, 8)
train_set (120, 8)
test_set (30, 8)
xx (120, 5)
y (120, 3)


In [39]:
x = tf.placeholder(tf.float32)
w = tf.Variable(tf.zeros([5,3]))
z = tf.matmul(x, w) # (120,3) = (120,5) * (120,3)
hf = tf.nn.softmax(z)
cost = tf.reduce_mean(tf.reduce_sum(y*-tf.log(hf), axis = 1))

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

for i in range(2001):
    sess.run(train, feed_dict={x:xx})
    if i % 200 == 0 :
        print(i, sess.run(cost, feed_dict={x:xx}))

0 1.0858719
200 0.5771965
400 0.47585264
600 0.4235805
800 0.38760206
1000 0.35984558
1200 0.33722714
1400 0.31822267
1600 0.30194062
1800 0.28779697
2000 0.27537963


In [43]:
# test 데이터셋을 이용한 모델검증

xx = test_set[:,:-3] 
print("xx",xx.shape)
y = test_set[:,-3:]
print("y",y.shape)

yhat = sess.run(hf, feed_dict={x:xx})
print("\nyhat\n",yhat)

xx (30, 5)
y (30, 3)

yhat
 [[9.6243662e-01 3.7443753e-02 1.1969174e-04]
 [8.1496149e-01 1.8313871e-01 1.8998071e-03]
 [9.4292545e-01 5.6707352e-02 3.6727288e-04]
 [9.3218017e-01 6.7333922e-02 4.8593152e-04]
 [9.3477923e-01 6.4790159e-02 4.3053160e-04]
 [9.1286993e-01 8.6612165e-02 5.1792967e-04]
 [9.6230567e-01 3.7568856e-02 1.2544835e-04]
 [9.3470258e-01 6.4909935e-02 3.8758674e-04]
 [9.6364492e-01 3.6267221e-02 8.7860179e-05]
 [9.4487053e-01 5.4931305e-02 1.9815772e-04]
 [1.8128432e-02 5.4351842e-01 4.3835312e-01]
 [2.5485115e-02 6.1918533e-01 3.5532945e-01]
 [4.7125529e-02 7.2125375e-01 2.3162067e-01]
 [9.6438192e-02 7.1699411e-01 1.8656772e-01]
 [3.1403296e-02 6.1277360e-01 3.5582313e-01]
 [5.6197319e-02 6.7787105e-01 2.6593164e-01]
 [4.4726428e-02 6.5059632e-01 3.0467725e-01]
 [4.4670098e-02 7.3072410e-01 2.2460587e-01]
 [1.9530220e-01 6.9732708e-01 1.0737081e-01]
 [4.6829741e-02 6.6835839e-01 2.8481191e-01]
 [1.2283019e-03 1.9308437e-01 8.0568725e-01]
 [6.2384736e-03 4.1091466e-

In [57]:
# tensorflow를 이용한 검증

yhat2 = sess.run(tf.argmax(yhat, axis = 1))
print("예측값 : ", yhat2)
y2 = sess.run(tf.argmax(y, axis = 1))
print("실제값 : ",y2)

equal = sess.run(tf.equal(yhat2,y2))
print(equal)

cast = sess.run(tf.cast(equal, tf.float32))
print(cast)

mean = sess.run(tf.reduce_mean(cast))
print(mean)

예측값 :  [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
실제값 :  [0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1.]
1.0


* * *

In [58]:
# numpy를 이용한 검증

yhat2 = np.argmax(yhat, axis = 1)
print(yhat2)
y2 = np.argmax(y, axis = 1)
print(y2)

equal = (yhat2 == y2)
print(equal)

mean = np.mean(equal)
print(mean)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]
1.0
